### ISSUE TITLE
vignette and README.md

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/updateObject#1]
Hi, for review to proceed there really should be a vignette, however brief.

**Comment by hpages** [comment]
I'll add a short vignette. I didn't remember this being a requirement for infrastructure packages but it seems that this yet another privilege that went out of fashion recently :wink: (in [BiocCheck 1.25.9](https://github.com/Bioconductor/BiocCheck/commit/5d67a66bbe4d820cc87f25f51d0e82215b91e2fd)). Ouch!

**Comment by hpages** [comment]
Done
